<center><h1>Lab 2</h1></center>

<center><h2>Sains Data Genap 2020/2021</h2></center>

<center><h2>Deadline: 7 Maret 2021, 23.55 WIB</h2></center>

### Petunjuk Umum

1.   Buka dokumen Jupyter Notebook **Lab2.ipynb** yang telah disediakan di scele.
2.   Lengkapi data **NPM**, **KOLABORATOR** (jika ada), dan **REFERENSI** (jika ada), pada cell di bawah Petunjuk Umum.
3.   Jalankan kode yang telah disediakan dan perhatikan dengan saksama apa yang potongan kode tersebut lakukan beserta dengan keluarannya. Jawablah **pertanyaan pada bagian akhir dokumen** sesuai dengan perintah yang diberikan.
4.   Dokumen Jupyter Notebook yang telah dijawab dikumpulkan dengan format penamaan **KodeAsdos_Lab2_NPM_Nama.ipynb**. Contoh: LI_Lab2_1706979341_Lulu Ilmaknun Qurotaini.ipynb
5.    Kumpulkan pada submisi yang telah disediakan di scele sebelum **7 Maret 2021, 23.55 WIB**.

In [1]:
#Input NPM
NPM = "1806205722"

#Input NPM teman yang berkolaborasi dengan Anda dalam mengerjakan tugas ini (jika ada)
KOLABORATOR = []

#Input link referensi atau sumber lain yang Anda gunakan dalam menyelesaikan tugas ini (jika ada)
REFERENSI = []

# Pengenalan NumPy

[NumPy](https://numpy.org/) (Numerical Python) adalah library Python yang berfokus pada <i>Scientific computing</i>. NumPy menyerupai List pada Python, hanya saja NumPy memiliki beberapa kelebihan seperti penggunaan memory yang lebih kecil, runtime yang lebih cepat, dan memudahkan kita melakukan operasi vektor dan matriks. Hal ini menyebabkan NumPy menjadi salah satu library yang banyak digunakan dalam proses analisis data.

In [2]:
# import library NumPy
import numpy as np

## Array NumPy

Untuk membuat sebuah array baru, kita dapat membuat python List kemudian diubah menjadi NumPy array

In [3]:
# Membuat python List
py_lst = [1,2,3,4,5]
# Membuat numpy array
np_arr = np.array(py_lst)
np_arr

array([1, 2, 3, 4, 5])

Atau kita juga dapat menggunakan fungsi <code>array()</code> yang terdapat pada NumPy

In [4]:
# Membuat numpy array
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

Terdapat beberapa fungsi bawaan yang dapat digunakan untuk membuat array

In [5]:
# Membuat array dengan nilai 0 sebanyak 5
print("np.zeros(5) : ",np.zeros(5))

# Membuat array dengan nilai 1 sebanyak 5
print("np.ones(5) : ",np.ones(5))

# Membuat array dengan nilai dalam range 1 sampai 10 dengan step sebesar 2
print("np.arange(1,10,2) : ",np.arange(1,10,2))

# Membuat array dengan nilai dalam range 1 sampai 10 sebanyak 4 dengan interval yang sama
print("np.linspace(1,10,4) : ",np.linspace(1,10,4))

np.zeros(5) :  [0. 0. 0. 0. 0.]
np.ones(5) :  [1. 1. 1. 1. 1.]
np.arange(1,10,2) :  [1 3 5 7 9]
np.linspace(1,10,4) :  [ 1.  4.  7. 10.]


## Array Multidimensi

Selain array 1 dimensi, numpy juga mempunyai kemampuan untuk membuat dan memanipulasi array multidimensi dengan mudah

In [6]:
# Membuat numpy array multidimensi / matrix
mult_arr = np.array([[1,2,3],[4,5,6],[10,20,30]])
mult_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

## Menampilkan Atribut dari Array

Untuk mengetahui jumlah elemen dari sebuah array, kita dapat menggunakan <code>size</code>

In [7]:
print(arr)
# Menunjukkan ukuran array
arr.size

[10 20 30 40 50]


5

In [8]:
print(mult_arr)
# Menunjukkan ukuran array multidimensi
mult_arr.size

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


9

Menggunakan <code>ndim</code> kita dapat mengetahui jumlah dimensi atau rank dari sebuah array

In [9]:
# Menunjukkan rank dari array
mult_arr.ndim

2

Untuk mengetahui ukuran dari setiap dimensi array menggunakan <code>shape</code>

In [10]:
# Mengetahui shape sebuah array
arr.shape

(5,)

In [11]:
# Mengetahui shape sebuah array multidimensi
mult_arr.shape

(3, 3)

## Cek Tipe

Kita dapat mengetahui tipe dari sebuah objek menggunakan fungsi <code>type()</code>

In [12]:
py_lst = [1,2,3,4,5]
type(py_lst)

list

In [13]:
np_arr

array([1, 2, 3, 4, 5])

Ketika mengecek numpy array menggunakan fungsi <code>type</code>, maka kita akan mendapatkan <b>numpy.ndarray</b>

In [14]:
# Mengecek tipe dari array
type(np_arr)

numpy.ndarray

Untuk mengecek tipe data yang ada di dalam sebuah numpy array dapat menggunakan <code>dtype</code>

In [15]:
# Mengecek tipe data dari array
np_arr.dtype

dtype('int64')

## Indexing, Slicing, dan Assigning Value pada Array

In [16]:
# Membuat numpy array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

Mengakses elemen pertama dari array

In [17]:
a[0]

1

In [18]:
# Membuat numpy array multidimensi
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# Mengakses elemen baris kedua, kolom ketiga dari sebuah array multidimensi
A[1,2]

6

In [20]:
# Cara lain mengakses elemen baris kedua, kolom ketiga dari sebuah array multidimensi
A[1][2]

6

Kita dapat melakukan slicing pada numpy array seperti pada List

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
# Slice elemen index 1 sampai 3
b = a[1:4]
b

array([2, 3, 4])

In [23]:
#Slice elemen index 1 sampai ke-1 dari belakang
a[1:-1]

array([2, 3, 4])

Kita juga dapat melakukan slicing pada array multidimensi

In [24]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#Slice elemen dari baris pertama, kolom 1 serta 2
A[0][0:2]

array([1, 2])

In [26]:
#Slice elemen dari kolom pertama, baris 2 serta 3
A[1:3,0]

array([4, 7])

In [27]:
# Slice kolom kedua
A[:,1]

array([2, 5, 8])

Kita dapat mengubah value dari sebuah array. 


In [28]:
# Mengubah elemen kelima array a menjadi 500
a[4] = 500
a

array([  1,   2,   3,   4, 500])

In [29]:
# Mengubah elemen baris pertama kolom pertama array multidimensi A menjadi 100
A[0][0] = 100
A

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

Kita dapat menggunakan sebuah list untuk memilih indeks secara spesifik

In [30]:
# Membuat list berisi indeks
lst = [0,3,4]

In [31]:
# Menggunakan list untuk memilih elemen
c = a[lst]
c

array([  1,   4, 500])

Selain itu, kita juga bisa meng-assign elemen pada indeks di list dengan value baru

In [32]:
# Assign value baru pada indeks di list
a[lst] = 1234
a

array([1234,    2,    3, 1234, 1234])

## Operasi pada Array

In [33]:
x = np.array([10, 15, 20, 25, 30])
y = np.array([30, 25, 20, 15, 10])

In [34]:
# Penjumlahan Array
print("Penjumlahan Array : ", x + y)

# Pengurangan Array
print("Pengurangan Array : ", x - y)

Penjumlahan Array :  [40 40 40 40 40]
Pengurangan Array :  [-20 -10   0  10  20]


In [35]:
# Penjumlahan Array dengan  bilangan konstan
print("Penjumlahan dengan sebuah bilangan : ", x + 3)

# Perkalian Array dengan bilangan konstan
print("Perkalian dengan sebuah bilangan : ", x * 2)

Penjumlahan dengan sebuah bilangan :  [13 18 23 28 33]
Perkalian dengan sebuah bilangan :  [20 30 40 50 60]


In [36]:
m = np.array([1,2])
n = np.array([0,1])

# Perkalian 2 buah array
print ("Perkalian array m dan n : ", m * n)

# Dot product dari 2 buah array
print ("Dot product m dan n : ", np.dot(m,n))

Perkalian array m dan n :  [0 2]
Dot product m dan n :  2


## Operasi pada Array Multidimensi / Matrix

Operasi pada array juga berlaku pada array multidimensi / matrix

In [37]:
X = np.array([[1,0],[0,1]])
Y = np.array([[0,1],[1,0]])

In [38]:
# Penjumlahan matrix
print("Penjumlahan")
print(X + Y)

# Pengurangan Array
print("Pengurangan")
print(X - Y)

Penjumlahan
[[1 1]
 [1 1]]
Pengurangan
[[ 1 -1]
 [-1  1]]


In [39]:
# Penjumlahan Matrix dengan  bilangan konstan
print("Penjumlahan dengan sebuah bilangan : ")
print(X + 2)

# Perkalian Matrix dengan bilangan konstan
print("Penjumlahan dengan sebuah bilangan : ")
print(X * 2)

Penjumlahan dengan sebuah bilangan : 
[[3 2]
 [2 3]]
Penjumlahan dengan sebuah bilangan : 
[[2 0]
 [0 2]]


In [40]:
M = np.array([[1,2],[2,1]])
N = np.array([[2,1],[1,2]])

# Perkalian elemen dari 2 buah matrix
print("Perkalian antar elemen M dan N : ")
print (M * N)

# Dot product dari 2 buah matrix (perkalian matrix)
print("Perkalian Matrix M dan N : ")
print (np.dot(M,N))

Perkalian antar elemen M dan N : 
[[2 2]
 [2 2]]
Perkalian Matrix M dan N : 
[[4 5]
 [5 4]]


In [41]:
P = np.array([[1,2],[3,4]])

# Matrix P
print(P)

# Membuat matrix transpose dari matrix P
print("Transpose : ")
print(np.transpose(P))

# Membuat matrix invers dari matrix P
print("Invers : ")
print(np.linalg.inv(P))

[[1 2]
 [3 4]]
Transpose : 
[[1 3]
 [2 4]]
Invers : 
[[-2.   1. ]
 [ 1.5 -0.5]]


## Operasi Statistik pada Array

In [42]:
stat_arr = np.array([7, 7, 6, 6, 5, 7, 5, 9, 4, 2, 4, 2, 7, 7, 7, 3, 4, 4, 8, 7, 8, 6,
       4, 1, 1])
stat_arr

array([7, 7, 6, 6, 5, 7, 5, 9, 4, 2, 4, 2, 7, 7, 7, 3, 4, 4, 8, 7, 8, 6,
       4, 1, 1])

In [43]:
# Nilai rata-rata dari sebuah array
print("Nilai rata-rata : ", np.mean(stat_arr))

# Nilai maksimal dari sebuah array
print("Nilai maks : ", np.max(stat_arr))

# Nilai unik dari sebuah array
print("Nilai unik : ", np.unique(stat_arr))

#Sort nilai pada array
print("Sorted : ", np.sort(stat_arr))

Nilai rata-rata :  5.24
Nilai maks :  9
Nilai unik :  [1 2 3 4 5 6 7 8 9]
Sorted :  [1 1 2 2 3 4 4 4 4 4 5 5 6 6 6 7 7 7 7 7 7 7 8 8 9]


# Pertanyaan Lab 2

Jawab setiap pertanyaan pada _cell_ di bawah _cell_ pertanyaan. Jawaban boleh lebih dari 1 _cell_ dan juga kombinasi antara _cell_ kode atau _markdown_ jika memang diperlukan.

1. Buatlah sebuah matriks nol berukuran 3x3! Kemudian jumlahkan setiap elemennya dengan angka 1!

In [63]:
# Jawaban
mat_ones = np.ones([3,3])
print(f'Matriks 3x3 dengan nilai 1 di setiap elemen:\n{mat_ones}')
new_mat = mat_ones + 1
print(f"Setiap elemen matrix diatas ditambah 1:\n{new_mat}")

Matriks 3x3 dengan nilai 1 di setiap elemen:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Setiap elemen matrix diatas ditambah 1:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


<hr>

In [102]:
arr_2 = np.array([1,2,3,4,5,6,7,8.5])
arr_2.dtype

dtype('float64')

2. Jalankan _cell_ di atas! Mengapa tipe data yang didapatkan dari <code>arr_2.dtype</code> bertipe float padahal ada elemen yang bertipe integer juga? Jelaskan secara singkat!

In [101]:
# Jawaban

Karena numpy mencari generalisasi tipe dari array tersebut dan mengubahnya setiap elemen ke tipe generalisasi yang ditemukan. tipe float dapat mencakup data integer dan data float tanpa kehilangan presisi, sedangkan jika tipe integer yang diplihi sebagai generaliasi, maka elemen dengan tipe data float akan kehilangan presisi dari datanya.

<hr>

3. Terdapat 2 buah array v dan w seperti di bawah. Lakukan operasi v + w __(tanpa diubah menjadi numpy array terlebih dahulu)__!


In [47]:
v = [1,2,3,4,5]
w = [6,7,8,9,10]

In [64]:
# Jawaban
v + w

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Ubahlah array v dan w menjadi numpy array dan lakukan operasi penjumlahan (np_v + np_w)!

In [65]:
# Jawaban
np.array(v) + np.array(w)

array([ 7,  9, 11, 13, 15])

Apakah perbedaan kedua operasi di atas? (Sebelum dan sesudah diubah menjadi numpy array)

In [50]:
# Jawaban
Operasi Pertama akan melakukan konkantenasi List W ke List V, sedangkan operasi terkahir 
menambahkan elemen matriks V dan W sesuai dengan letak baris dan kolom yang sama.

<hr>

In [51]:
V = np.array([[2,3,2],[1,2,1],[3,2,1]])
W = np.array([[1,1,2],[2,3,1],[2,2,2]])

4. Terdapat matrix V dan W seperti pada _cell_ di atas, lakukan operasi perkalian matrix V dan W! Kemudian buatlah sebuah matrix baru yang isinya akar dari setiap elemen dari hasil perkalian matrix tersebut! Tampilkan matrix transpose dari matrix akar tersebut! (Hint : Anda dapat menggunakan fungsi <code>sqrt</code> dari NumPy)

In [72]:
#Jawaban
product_VW = np.dot(V, W)
print(f"Hasil kali matriks VW:\n{product_VW}\n")

root_product = np.sqrt(product_VW)
print(f"Akar tiap elemen dari perkalian matriks:\n{root_product}\n")

trsp_root = np.transpose(root_product)
print(f"Transpose matrix akar sebelumnya:\n{trsp_root}")

Hasil kali matriks VW:
[[12 15 11]
 [ 7  9  6]
 [ 9 11 10]]

Akar tiap elemen dari perkalian matriks:
[[3.46410162 3.87298335 3.31662479]
 [2.64575131 3.         2.44948974]
 [3.         3.31662479 3.16227766]]

Transpose matrix akar sebelumnya:
[[3.46410162 2.64575131 3.        ]
 [3.87298335 3.         3.31662479]
 [3.31662479 2.44948974 3.16227766]]


<hr>

In [53]:
arr_5 = np.array([89, 33, 13, 13, 11, 49, 96,  1, 79, 76, 88, 16, 78, 14, 26, 26, 20,
        9, 51, 88, 19, 14,  7, 51, 45, 76, 41, 11, 34, 36, 77,  8, 55,  4,
        8,  1, 47, 27, 67,  7, 45, 96, 69, 21, 37, 32, 41, 43, 49, 53])

5. Terdapat array seperti _cell_ di atas, cari dan tampilkan rata-rata, nilai maksimum, minimum, median, standar deviasi, variance, dan ukuran dari array tersebut!

In [88]:
#Jawaban
print(f"Rata-rata: {arr_5.mean()}")
print(f"Nilai Maksimum: {arr_5.max()}")
print(f"Nilai Minimum: {arr_5.min()}")
print(f"Median: {np.median(arr_5)}")
print(f"Standar Deviasi: {np.std(arr_5)}")
print(f"Ukuran array: {arr_5.size}")

Rata-rata: 39.94
Nilai Maksimum: 96
Nilai Minimum: 1
Median: 36.5
Standar Deviasi: 28.005292356981386
Ukuran array: 50


<hr>